### ISSUE TITLE
Sequence Revoca della RT errato

### ISSUE THREAD

**Issue by nardil** [italia/pagopa-specifichepagamenti-docs#16]
Nel paragrafo [8.2.4 Revoca della RT](https://docs.italia.it/italia/pagopa/pagopa-specifichepagamenti-docs/it/bozza/_docs/Capitolo8.html#revoca-della-rt) viene presentato un sequence diagram dove la comunicazione risulta invertita.
![pagopa-specifichepagamenti-docs/_docs/media/cap8/image17.png](https://github.com/italia/pagopa-specifichepagamenti-docs/blob/master/_docs/media/cap8/image17.png?raw=true)

**Comment by danielelandro** [comment]
Abbiamo pubblicato la versione 2.2 delle SANP
