### ISSUE TITLE
Discrepanza strategie di retry RTPush

### ISSUE THREAD

**Issue by venturipaolo** [italia/pagopa-specifichepagamenti-docs#20]
Nella tabella 9 del paragrafo 13.3.5 c'e' scritto che si "triggera" la retry nel caso di PPT_STAZIONE_INT_PA_TIMEOUT o PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE o nessuna risposta.
Poco piu' sotto invece si dice che, a fronte di PPT_STAZIONE_INT_PA_TIMEOUT o PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE, il PSP pone la RT nella coda PULL, pur avendo il PSP facoltà di reiterare l’invio della RT in modalità PUSH.
La retry e' quindi facoltativa o obbligatoria nel caso di PPT_STAZIONE_INT_PA_TIMEOUT o PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE ?

**Comment by giannipapetti** [comment]
Grazie, prendiamo in carico la segnalazione.

**Comment by giannipapetti** [comment]
Il processo sarà chiarito nel prossimo rilascio documentale.
