### ISSUE TITLE
Stati di una RPT

### ISSUE THREAD

**Issue by nardil** [italia/pagopa-specifichepagamenti-docs#22]
Mi risulta che non siano più indicati gli stati del ciclo di vita di una RPT. In particolare quali sono i risultati possibili della primitiva nodoChiediStatoRPT e quali di questi siano finali nel ciclo di vita.

**Comment by nardil** [comment]
... e per quali stati finali e' consentito il riuso dello IUV

**Comment by gammam** [comment]
Aggiunto all'interno del capitolo 13, nella prossima patch
