### ISSUE TITLE
identificativoCarrello 

### ISSUE THREAD

**Issue by gammam** [italia/pagopa-specifichepagamenti-docs#23]
l'identificativoCarrello è una stringa di 35 caratteri, mentre l'algoritmo proposto compone una stringa di 36 caratteri 

> a.	identificativoCarrello: deve risultare univoco all’interno del Sistema pagoPA; il codice deve essere composto secondo il seguente formato:
> <Anno(4)><idDominio(11)><codice Sorgente(2)><Progressivo(19)>

verrà modificato il progressivo a 18 caratteri

**Comment by nardil** [comment]
Nella regola di composizione dell'identificativoCarrello sono inclusi i campi idDominio e codiceSorgente cosi descritti:

> _idDominio_: valore del medesimo campo dell’RPT
> _codiceSorgente_: codice che permette di distinguere la sorgente del codice che genera l’identificativo Carrello (può coincidere con il codice segregazione della Stazione)

Nel caso dell'idDominio, trattandosi di un carrello di RPT, puo' non essere lo stesso in ogni RPT. E' quindi ambiguo come valorizzare il campo.
Nel caso del codiceSorgente, non e' chiaro se e' un campo a discrezione dell'ente o meno (se si, perche' non viene assorbito dal progressivo?).

Il mio suggerimento e' modificare la sintassi come segue:

`<Anno(4)><idIntermediario(11)><applicationCode(2)><Progressivo(18)>`

dove i campi idIntermediario e applicationCode di fatto individuano la stazione che deve essere sempre la stessa nelle RPT del carrello. Mi sembra che si eliminano cosi le ambiguita con maggior garanzia di univocita.
